server:
  port:8080

spring:
  application:
    name: vehicle
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/vehicle
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true